# Use Node.js LTS as the base image
FROM node:18.17.0

# Set the working directory
WORKDIR /frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the application
RUN npm run build

# Expose the frontend port
EXPOSE 3000

# Run the application
CMD ["npm", "run", "start"]