
services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "${PORT}:${PORT}"  # Reference from .env
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}

