# Use an official Node.js image as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /backend

# Copy the package jsons 
COPY package*.json ./

# Install backend dependencies
RUN npm install

# Copy the directory
COPY . .

# Copy the src code and test code to the container
COPY src/ ./src
RUN npm run build

# Expose port 3000
EXPOSE ${PORT}

# Start the server from the src directory
CMD ["node", "./dist/index.js"]